pr: none
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - docs/
    - environment_setup/
    - charts/
    - ml_service/util/create_scoring_image.py

variables:
- group: devopsforai-aml
# Choose from default, build_train_pipeline_with_r.py, or build_train_pipeline_with_r_on_dbricks.py
- name: build-train-script
  value: 'build_train_pipeline.py'
# Automatically triggers the train, evaluate, register pipeline after the CI steps. 
# Uncomment to set to false or add same variable name at queue time with value of false to disable.
# - name: auto-trigger-training
#   value: false

stages:
- stage: 'Model_CI'
  displayName: 'Model CI'
  jobs:
  - job: "Model_CI_Pipeline"
    displayName: "Model CI Pipeline"
    pool: 
      vmImage: 'ubuntu-latest'
    container: mcr.microsoft.com/mlops/python:latest
    timeoutInMinutes: 0
    steps:
    - template: azdo-base-pipeline.yml
    - script: |
        # Invoke the Python building and publishing a training pipeline
        python3 $(Build.SourcesDirectory)/ml_service/pipelines/build_train_pipeline.py
      failOnStderr: 'false'
      env:
        SP_APP_SECRET: '$(SP_APP_SECRET)'
      displayName: 'Publish Azure Machine Learning Pipeline'
    - script: |
        # Invoke the Python building and publishing a deployment pipeline
        python3 $(Build.SourcesDirectory)/ml_service/pipelines/build_deploy_pipeline.py
      failOnStderr: 'false'
      env:
        SP_APP_SECRET: '$(SP_APP_SECRET)'
      displayName: 'Publish Azure Machine Learning Deployment Pipeline'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        Contents: |
          code/scoring/**
          ml_service/pipelines/**
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        ArtifactName: 'mlops-pipelines'
        publishLocation: 'container'
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        TargetPath: '$(Build.ArtifactStagingDirectory)'